CONFIG_NAME: 'pos-devnet'

# Genesis
# ---------------------------------------------------------------
# `2**14` (= 16,384)
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 1
MIN_GENESIS_TIME: 1750662103
GENESIS_FORK_VERSION: 0x00000084
GENESIS_DELAY: 30

MAX_EFFECTIVE_BALANCE: 32000000000
# Forking
# ---------------------------------------------------------------
# Some forks are disabled for now:
#  - These may be re-assigned to another fork-version later
#  - Temporarily set to max uint64 value: 2**64 - 1

# Altair
ALTAIR_FORK_VERSION: 0x01000084
ALTAIR_FORK_EPOCH: 2

# Merge
BELLATRIX_FORK_VERSION: 0x02000084
BELLATRIX_FORK_EPOCH: 4

#  TBD: 2**64-1 is a placeholder
TERMINAL_TOTAL_DIFFICULTY: 1000

# Sharding
SHARDING_FORK_VERSION: 0x03000084
SHARDING_FORK_EPOCH: 18446744073709551615

# Time parameters
# ---------------------------------------------------------------
# 5 seconds
SECONDS_PER_SLOT: 5
SLOTS_PER_EPOCH: 5
# 14 (estimate from Eth1 mainnet)
SECONDS_PER_ETH1_BLOCK: 5
# 2**8 (= 256) epochs ~27 hours
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 256 
# 2**8 (= 256) epochs ~27 hours
SHARD_COMMITTEE_PERIOD: 256
# 2**11 (= 2,048) Eth1 blocks ~8 hours
ETH1_FOLLOW_DISTANCE: 5

EPOCHS_PER_ETH1_VOTING_PERIOD: 1

# Validator cycle
# ---------------------------------------------------------------
# 2**2 (= 4)
INACTIVITY_SCORE_BIAS: 4
# 2**4 (= 16)
INACTIVITY_SCORE_RECOVERY_RATE: 16
# 2**4 * 10**9 (= 16,000,000,000) Gwei
EJECTION_BALANCE: 16000000000
# 2**2 (= 4)
MIN_PER_EPOCH_CHURN_LIMIT: 4
# 2**16 (= 65,536)
CHURN_LIMIT_QUOTIENT: 4096

# Deposit contract
# ---------------------------------------------------------------
DEPOSIT_CHAIN_ID: 1337
DEPOSIT_NETWORK_ID: 1337
DEPOSIT_CONTRACT_ADDRESS: 0x4242424242424242424242424242424242424242
