PRESET_BASE: 'gnosis'
CONFIG_NAME: 'joc-1'

# Genesis
# ---------------------------------------------------------------
# `2**14` (= 16,384)
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 3
MIN_GENESIS_TIME: 1753840307
GENESIS_FORK_VERSION: 0x00000084
GENESIS_DELAY: 25
EPOCHS_PER_ETH1_VOTING_PERIOD: 1
MAX_EFFECTIVE_BALANCE: 64000000000

# Forking
# ---------------------------------------------------------------
# Some forks are disabled for now:
#  - These may be re-assigned to another fork-version later
#  - Temporarily set to max uint64 value: 2**64 - 1

# Altair
ALTAIR_FORK_VERSION: 0x01000084
ALTAIR_FORK_EPOCH: 1

# Merge
BELLATRIX_FORK_VERSION: 0x02000084
BELLATRIX_FORK_EPOCH: 3

#  TBD: 2**256-1 is a placeholder
TERMINAL_TOTAL_DIFFICULTY: 80
TERMINAL_BLOCK_HASH: 0x0000000000000000000000000000000000000000000000000000000000000000
TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: 18446744073709551615

# shanghai fork
CAPELLA_FORK_VERSION: 0x03000084
CAPELLA_FORK_EPOCH: 18446744073709551615

# Cancun
DENEB_FORK_VERSION: 0x04000084
DENEB_FORK_EPOCH: 18446744073709551615

# Prague
ELECTRA_FORK_VERSION: 0x05000084
ELECTRA_FORK_EPOCH: 18446744073709551615

# Sharding
# SHARDING_FORK_VERSION: 0x03000084
# SHARDING_FORK_EPOCH: 18446744073709551615

# Time parameters
# ---------------------------------------------------------------
# 5 seconds
SECONDS_PER_SLOT: 5
SLOTS_PER_EPOCH: 5
# 14 (estimate from Eth1 mainnet)
SECONDS_PER_ETH1_BLOCK: 5
# 2**8 (= 256) epochs ~27 hours
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 5 
# 2**8 (= 256) epochs ~27 hours
SHARD_COMMITTEE_PERIOD: 10
# 2**11 (= 2,048) Eth1 blocks ~8 hours
ETH1_FOLLOW_DISTANCE: 1

# Validator cycle
# ---------------------------------------------------------------
# 2**2 (= 4)
INACTIVITY_SCORE_BIAS: 4
# 2**4 (= 16)
INACTIVITY_SCORE_RECOVERY_RATE: 16
# 2**4 * 10**9 (= 16,000,000,000) Gwei
EJECTION_BALANCE: 16000000000
# 2**2 (= 4)
MIN_PER_EPOCH_CHURN_LIMIT: 4
# 2**16 (= 65,536)
CHURN_LIMIT_QUOTIENT: 4096
PROPOSER_SCORE_BOOST: 40

# Deposit contract
# ---------------------------------------------------------------
DEPOSIT_CHAIN_ID: 84
DEPOSIT_NETWORK_ID: 84
DEPOSIT_CONTRACT_ADDRESS: 0x4242424242424242424242424242424242424242
